name: CompatHelper
on:
  schedule:
    - cron: '37 3 * * *'
  workflow_dispatch:
jobs:
  CompatHelper:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/compat_helper.yml@master
    with:
      use_FuseRegistry: false
